---
- name: Upgrade npm
  become: true
  shell: |
    npm install -g npm@latest

- name: Copy compiled files
  unarchive:
      src: /root/project/backend.tar.gz
      dest: /home/ubuntu/

- name: Executing node
  shell: |
    cd backend
    npm install
    npm run build
    # npm run start
    pm2 start npm --no-automation --name "backend" -- run start
    cd ./dist
    pm2 start main.js
